project:
  type: website
  output-dir: docs

website:
  title: Wprowadzenie do Programowania - Laboratorium
  description: "Wprowadzenie do programowania - laboratorium dla studentów WAT w Warszawie"
  site-url: https://sebkaz-teaching.github.io/wdplab2026
  sidebar:
    style: "docked"
    contents:
      - index.qmd
  page-footer: "Copyright 2026, Sebastian Zając"
format:
  html:
    page-layout: article
    css: style.css
    theme: cosmo
    toc: true
    toc-depth: 2
    toc-title: "**Sections**"
    self-contained-math: true
    code-overflow: wrap
    highlight-style: dark
    code-block-background: true
    link-external-newwindow: true
